// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MusicPlaylistRESTClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UpdateSongRequest
    {
        /// <summary>
        /// Initializes a new instance of the UpdateSongRequest class.
        /// </summary>
        public UpdateSongRequest() { }

        /// <summary>
        /// Initializes a new instance of the UpdateSongRequest class.
        /// </summary>
        public UpdateSongRequest(string artist = default(string), string title = default(string), IList<string> genres = default(IList<string>))
        {
            Artist = artist;
            Title = title;
            Genres = genres;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "artist")]
        public string Artist { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "genres")]
        public IList<string> Genres { get; set; }

    }
}
